extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:react/recommended
settings:
  react:
    version: detect
plugins:
  - '@typescript-eslint'
  - react
parser: '@typescript-eslint/parser'
rules:
  react/prop-types: 0
